name: coapd
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A sample CoAP server
description: |
  A sample CoAP server to explore snapcraft build environment

grade: devel
confinement: devmode
base: core18

parts:
  coapd:
    plugin: make
    source: src/coapd
